import test from 'node:test'
import assert from 'node:assert/strict'
import { chooseEpisodeForSlot, parseDuration, sortEpisodesNewestFirst } from '../src/utils/episodes.js'
import { normalizeFeed, validateFeedUrl } from '../api/_lib/feed.js'
import { normalizeChart } from '../api/_lib/appleCharts.js'
import { migrateState } from '../src/utils/persistence.js'
import { planStack, podcastKey, scoreEpisode } from '../src/data/catalogue.js'
import { daysFromToday, visibleStackDays } from '../src/utils/stackDisplay.js'
test('parses common RSS durations',()=>{assert.deepEqual(parseDuration('1:02:30'),{durationSeconds:3750,durationMinutes:63});assert.equal(parseDuration('').durationMinutes,null)})
test('migrates legacy duration windows to simple selected days',()=>assert.deepEqual(migrateState({selectedDays:{Monday:'45–60 minutes',Tuesday:{targetMinutes:20},Wednesday:false}}).selectedDays,{Monday:true,Tuesday:true}))
test('sorts episodes newest first',()=>assert.equal(sortEpisodesNewestFirst([{id:1,releaseDate:'2024-01-01'},{id:2,releaseDate:'2025-01-01'}])[0].id,2))
test('duration has no scoring effect',()=>assert.equal(chooseEpisodeForSlot([{id:'long',durationMinutes:180,interests:['News']},{id:'short',durationMinutes:5,interests:[]}],{}, {interests:['News']}).id,'long'))
test('normalizes RSS',()=>{const data=normalizeFeed({title:'Show',items:[{title:'Episode',guid:'g',pubDate:'2025-01-01',itunes:{duration:'47:00'}}]},'https://example.com/feed');assert.equal(data.episodes[0].durationMinutes,47);assert.equal(data.show.feedUrl,'https://example.com/feed')})
test('rejects unsafe URLs',async()=>{await assert.rejects(validateFeedUrl('http://127.0.0.1/rss'));await assert.rejects(validateFeedUrl('file:///tmp/feed'))})
test('normalizes ten usable Canadian chart rows',()=>{const data={feed:{results:Array.from({length:10},(_,i)=>({id:String(i+1),name:`Show ${i}`,artistName:'Host',url:`https://podcasts.apple.com/${i}`,genres:[]}))}};const result=normalizeChart(data,'ca',10,'now');assert.equal(result.length,10);assert.equal(result[0].rank,1);assert.equal(result[0].chartCountry,'ca')})
test('selected podcasts receive strongest priority and stack diversifies',()=>{const episodes=[{id:'a',guid:'a',podcastId:'fav',selectedPodcast:true,releaseDate:new Date().toISOString(),interests:[]},{id:'b',guid:'b',podcastId:'other',releaseDate:new Date().toISOString(),interests:['News']}];assert.ok(scoreEpisode(episodes[0],{interests:['News']})>scoreEpisode(episodes[1],{interests:['News']}));assert.equal(planStack(episodes,{Monday:true,Tuesday:true},{interests:['News']}).stack.length,2)})
test('weekly plan uses distinct podcast IDs when enough shows exist',()=>{const episodes=Array.from({length:5},(_,i)=>({id:`e${i}`,guid:`e${i}`,podcastId:`show${i}`,podcastName:`Show ${i}`,releaseDate:'2026-07-01'}));const stack=planStack(episodes,{Monday:true,Tuesday:true,Wednesday:true,Thursday:true,Friday:true},{}).stack;assert.equal(new Set(stack.map(podcastKey)).size,5)})
test('podcast identity falls back to feed URL and normalized name',()=>{assert.equal(podcastKey({feedUrl:'https://example.com/feed',podcastName:'A'}),'https://example.com/feed');assert.equal(podcastKey({podcastName:'  The DAILY! '}),'the daily')})
test('plan repeats at most twice when distinct shows cannot fill the week',()=>{const episodes=Array.from({length:6},(_,i)=>({id:`e${i}`,guid:`e${i}`,podcastId:i<3?'one':'two',releaseDate:`2026-07-0${i+1}`}));const stack=planStack(episodes,{Monday:true,Tuesday:true,Wednesday:true,Thursday:true,Friday:true},{}).stack;const counts=Object.values(Object.groupBy(stack,podcastKey)).map(x=>x.length);assert.ok(counts.every(count=>count<=2));assert.equal(stack.length,4)})
test('single selected show exception may fill selected days',()=>{const episodes=Array.from({length:3},(_,i)=>({id:`e${i}`,guid:`e${i}`,podcastId:'only',releaseDate:`2026-07-0${i+1}`}));assert.equal(planStack(episodes,{Monday:true,Tuesday:true,Wednesday:true},{selectedPodcasts:[{id:'only'}],interests:[]}).stack.length,3)})
test('day order starts on browser-local current day and wraps weekends',()=>{assert.deepEqual(daysFromToday(new Date(2026,6,28)),['Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday','Monday']);assert.deepEqual(daysFromToday(new Date(2026,7,1)).slice(0,3),['Saturday','Sunday','Monday'])})
test('empty days stay hidden while empty today remains first',()=>{const date=new Date(2026,6,31);const stack=[{day:'Saturday',id:'a'},{day:'Sunday',id:'b'}];assert.deepEqual(visibleStackDays(stack,{date}),['Friday','Saturday','Sunday']);assert.equal(visibleStackDays(stack,{date,showOpenDays:true}).length,7)})
