import { ArrowRight, Menu } from 'lucide-react'
import { Artwork } from '../UI'

export function PodStackLogo({stacked=false}){return <span className={`brand-logo ${stacked?'stacked':''}`}><img src="/brand/podstack-mark.svg" alt=""/><b>{stacked?<><span>Pod</span><span>Stack</span></>:'PodStack'}</b></span>}

export function EditorialRail({go}){const scroll=id=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'});return <aside className="editorial-rail"><button onClick={()=>go('landing')} aria-label="PodStack home"><PodStackLogo stacked/></button><nav aria-label="Homepage sections"><button className="active" onClick={()=>scroll('stacks')}><span>01</span>Explore</button><button onClick={()=>scroll('method')}><span>02</span>How it works</button><button onClick={()=>go('onboarding')}><span>03</span>Build my stack</button><button onClick={()=>go('onboarding')}><span>04</span>Sign in</button></nav><p>FORMULATION HOUSE<br/>FOR CURIOUS EARS</p><small>STACK NO.<br/><b>03</b></small></aside>}

export function MobileEditorialHeader({go}){return <header className="landing-mobile"><PodStackLogo/><span className="mobile-header-rule"/><button className="mobile-menu-label" onClick={()=>document.getElementById('stacks')?.scrollIntoView()}><Menu/> Menu</button><button className="mobile-build" onClick={()=>go('onboarding')}>Build my stack <ArrowRight/></button></header>}

export function FormulationLabel(){return <article className="formulation-panel"><header><img src="/brand/podstack-mark.svg" alt=""/><strong>PODSTACK</strong><span>FORMULATION / 003</span></header><div className="label-grid"><section className="label-number"><p>STACK NO.</p><b>03</b></section><section><p>FORMULATED FOR</p><h3>TUESDAY</h3></section><section><p>INCLUDES</p><h3>4 LISTENS</h3></section><section className="label-wide"><p>CATEGORIES</p><h3>CRIME / HISTORY / DEPTH / RESET</h3></section><section className="label-wide notes"><p>LISTENING NOTES</p><h3>Narrative, investigative, reflective</h3></section><section><p>PREPARED FOR</p><h3>MORNING COMMUTE</h3></section></div><footer>FORMULATION HOUSE FOR CURIOUS EARS <span>PS—03—TUE</span></footer><img className="label-barcode" src="/brand/barcode-strip.svg" alt=""/></article>}

export function PaperLayers({items}){return <div className="paper-layers" aria-label="Example PodStack formulation using abstract brand artwork"><i className="paper-sheet sheet-one"/><i className="paper-sheet sheet-two"/><i className="paper-sheet sheet-three"/><FormulationLabel/><div className="stack-artwork-group">{items.map(x=><Artwork item={x} key={x.title}/>)}</div><img className="collage-stamp" src="/brand/listening-formulated-stamp.svg" alt="" aria-hidden="true"/><img className="registration-detail" src="/brand/registration-marks.svg" alt="" aria-hidden="true"/><span className="catalogue-code">PS — WEEK 03 — CURATED MIX</span></div>}

export function CuratedStackCard({index,title,meta,items,accent,onClick}){return <button className="curated-card" style={{'--spine':accent}} onClick={onClick} aria-label={`Explore ${title}`}><span className="card-spine"/><span className="curated-content"><span className="card-utility">FORMULATION {String(index+1).padStart(2,'0')} / 04</span><b>{title}</b><span className="curated-art">{items.map((x,i)=><Artwork item={x} key={`${x.title}-${i}`}/>)}</span><small>{meta}</small></span><ArrowRight className="curated-arrow" aria-hidden="true"/></button>}

export function InsideStackPreview({item,onClick}){return <section className="inside-preview" aria-labelledby="inside-title"><div><p className="eyebrow">INSIDE A STACK / EXAMPLE</p><h2 id="inside-title">Today, considered.</h2></div><Artwork item={item}/><div className="inside-copy"><small>EXAMPLE FORMULATION · ABSTRACT ARTWORK</small><h3>{item.title}</h3><p>Selected to bring a reflective change of pace to the morning.</p><a href="https://podcasts.apple.com/ca/browse" target="_blank" rel="noreferrer">Browse real shows on Apple Podcasts <ArrowRight/></a></div><button className="secondary" onClick={onClick}>Build my stack <ArrowRight/></button></section>}
