import { ArrowRight } from 'lucide-react'
import { Artwork } from '../UI'

export function PodStackLogo({stacked=false}){return <span className={`brand-logo ${stacked?'stacked':''}`}><span className="sheet-mark" aria-hidden="true"><i/><i/></span><b>{stacked?<><span>Pod</span><span>Stack</span></>:'PodStack'}</b></span>}
export function EditorialRail({go}){const links=[['01','Explore','stacks'],['02','How it works','method'],['03','Build my stack','onboarding'],['04','Sign in','onboarding']];return <aside className="editorial-rail"><button onClick={()=>go('landing')} aria-label="PodStack home"><PodStackLogo stacked/></button><nav aria-label="Homepage">{links.map(([n,label,target],i)=><button key={n} className={i===0?'active':''} onClick={()=>target==='onboarding'?go(target):document.getElementById(target)?.scrollIntoView()}><span>{n}</span>{label}</button>)}</nav><p>FORMULATION HOUSE<br/>FOR CURIOUS EARS</p><small>STACK NO.<br/><b>03</b></small></aside>}
export function FormulationLabel(){return <article className="formulation-panel"><p>STACK NO. 03</p><dl><div><dt>Formulated for</dt><dd>The week ahead</dd></div><div><dt>Includes</dt><dd>Four considered listens</dd></div><div><dt>Categories</dt><dd>Crime / history / depth / reset</dd></div><div><dt>Listening notes</dt><dd>Narrative, investigative, reflective</dd></div></dl><span className="stack-stamp">LISTENING<br/>FORMULATED</span></article>}
export function PaperLayers({items}){return <div className="paper-layers" aria-label="Example podcast formulation"><i className="paper-sheet sheet-one"/><i className="paper-sheet sheet-two"/><FormulationLabel/><div className="stack-artwork-group">{items.slice(0,3).map(x=><Artwork item={x} key={x.title}/>)}</div><span className="catalogue-code">PS — WEEK 03 — CURATED MIX</span></div>}
export function CuratedStackCard({title,meta,items,accent,onClick}){return <button className="curated-card" style={{'--spine':accent}} onClick={onClick}><span className="card-spine"/><span className="curated-content"><b>{title}</b><span className="curated-art">{items.map(x=><Artwork item={x} key={x.title}/>)}</span><small>{meta}</small></span><ArrowRight className="curated-arrow" aria-hidden="true"/></button>}
export function InsideStackPreview({item,onClick}){return <section className="inside-preview"><div><p className="eyebrow">INSIDE A STACK</p><h2>Today, considered.</h2></div><Artwork item={item}/><div><small>{item.title}</small><h3>A purposeful selection for the shape of your day.</h3><p>Selected for variety · Example formulation</p></div><button className="secondary" onClick={onClick}>View full stack <ArrowRight/></button></section>}
