import { useEffect, useState } from 'react'
import { ArrowLeft, ArrowRight, CalendarPlus, Check, ChevronRight, CirclePlus, Clock3, LogOut, Menu, MoveRight, RefreshCw, Settings2, Trash2, X } from 'lucide-react'
import { discoveries, genres, services, buildStack } from './data/mockData'
import { usePrototype } from './hooks/usePrototype'
import { Artwork, ListenLink, LoadingStack, Logo, Tags } from './components/UI'

const paths = { landing: '/', onboarding: '/onboarding', today: '/today', stack: '/stack', discover: '/discover', profile: '/profile', email: '/continue-with-email', check: '/check-email', signin: '/sign-in' }
function useRoute() {
  const get = () => Object.entries(paths).find(([, path]) => path === location.pathname)?.[0] || 'landing'
  const [route, setRoute] = useState(get)
  useEffect(() => { const pop = () => setRoute(get()); addEventListener('popstate', pop); return () => removeEventListener('popstate', pop) }, [])
  const go = (name) => { history.pushState({}, '', paths[name]); setRoute(name); scrollTo(0, 0) }
  return [route, go]
}

function Nav({ route, go, signedIn }) {
  const [open, setOpen] = useState(false)
  const links = signedIn ? [['today','Today'],['stack','My Stack'],['discover','Discover']] : []
  return <header className="nav"><button className="brand-button" onClick={() => go(signedIn ? 'today' : 'landing')}><Logo/></button>
    {signedIn ? <><nav className={open ? 'navlinks open' : 'navlinks'} aria-label="Primary">{links.map(([key,label]) => <button className={route === key ? 'active' : ''} onClick={() => { go(key); setOpen(false) }} key={key}>{label}</button>)}<button className="avatar" onClick={() => go('profile')} aria-label="Open profile">AM</button></nav><button className="mobile-menu" onClick={() => setOpen(!open)} aria-label="Toggle navigation">{open ? <X/> : <Menu/>}</button></> : <nav className="signedout"><a href="#how">How it works</a><button onClick={() => go('signin')}>Sign in</button><button className="primary compact" onClick={() => go('onboarding')}>Start stacking</button></nav>}
  </header>
}

function SampleCard({ item, service = 'Spotify' }) { return <article className="sample-card"><div className="dayline"><b>{item.day.toUpperCase()}</b><span>{item.context} · {item.duration} minutes available</span></div><div className="episode-row"><Artwork item={item}/><div><small>{item.show}</small><h3>{item.title}</h3><p>{item.episodeDuration} min</p></div></div><Tags items={item.reasons}/><ListenLink item={item} service={service} compact/></article> }

function Landing({ go }) {
  const sample = buildStack().filter((_, i) => [0,1,3].includes(i))
  return <main><section className="landing-hero page"><div className="hero-copy"><p className="eyebrow">THE PLANNING LAYER FOR PODCASTS</p><h1>Your podcasts,<br/><em>already planned.</em></h1><p>Tell us when you listen, how much time you have, and what you like. Podstack builds a personalized schedule, so your next episode is always ready.</p><div className="button-row"><button className="primary" onClick={() => go('onboarding')}>Start stacking <ArrowRight/></button><a className="secondary" href="#example">See an example week</a></div><strong className="positioning">Your podcast app plays it. <span>Podstack plans it.</span></strong></div><div className="hero-stack" id="example"><p>Here’s what a week with Podstack looks like.</p>{sample.map(x => <SampleCard item={x} key={x.id}/>)}</div></section>
    <section className="how page" id="how"><p className="eyebrow">HOW IT WORKS</p><h2>We build the stack. You press play.</h2><div className="steps">{[['01','Set your routine','Tell Podstack when you listen and how much time you usually have.'],['02','Tell us your taste','Choose the genres, shows, topics, and formats you enjoy, along with anything you want to avoid.'],['03','Start stacking','Podstack builds your schedule. Open it each day, see what’s next, and continue in the podcast app you already use.']].map(x => <article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><blockquote>Your stack is your ready-made listening lineup: the right episodes, in the right order, sized to fit your week.</blockquote></section>
    <section className="cta"><h2>Know what you’re listening to before you leave.</h2><button className="primary" onClick={() => go('onboarding')}>Start stacking</button></section></main>
}

function Onboarding({ model, go }) {
  const { state, patch } = model; const [step, setStep] = useState(1); const [loading, setLoading] = useState(false); const [showInput, setShowInput] = useState('')
  const setWindows = windows => patch({ windows }); const updateWindow = (id, field, value) => setWindows(state.windows.map(x => x.id === id ? {...x,[field]:value} : x))
  const pref = state.preferences; const setPref = value => patch({ preferences: {...pref,...value} }); const toggle = (field, value) => setPref({ [field]: pref[field].includes(value) ? pref[field].filter(x=>x!==value) : [...pref[field], value] })
  const build = () => { setLoading(true); setTimeout(() => { patch({ stack: buildStack(state.windows), onboardingComplete: true }); setLoading(false); setStep(6) }, 1300) }
  if (loading) return <main className="center-page"><LoadingStack/><h1>Planning your week…</h1><p>Matching episodes to your schedule, preferences, and available time.</p><div role="status" className="sr-only">Building your listening plan</div></main>
  if (step === 6) return <main className="center-page account-ready"><Logo/><p className="success"><Check/> COMPLETE</p><h1>Your stack is ready.</h1><p>Create an account to save your plan, preferences, and listening history.</p><button className="primary" onClick={() => go('email')}>Continue with email</button><small>We’ll email you a secure sign-in link. No password required.</small><button className="link" onClick={() => go('signin')}>Already have an account? Sign in</button><button className="secondary" onClick={() => { patch({prototypeSignedIn:true}); go('today') }}>Explore prototype without an account</button></main>
  return <main className="onboarding page"><button className="back" onClick={() => step === 1 ? go('landing') : setStep(step-1)}><ArrowLeft/> Back</button><div className="progress" aria-label={`Step ${step} of 5`}><span style={{width:`${step*20}%`}}/></div><p className="eyebrow">STEP {step} OF 5</p>
    {step === 1 && <section><h1>When do you usually listen?</h1><p>Create a window for each day. Each one can have its own time and length.</p><div className="window-list">{state.windows.map(w => <article className="window" key={w.id}><label>Day<select value={w.day} onChange={e=>updateWindow(w.id,'day',e.target.value)}>{['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map(d=><option key={d}>{d}</option>)}</select></label><label>Context<input value={w.context} onChange={e=>updateWindow(w.id,'context',e.target.value)}/></label><label>Time<input type="time" aria-label={`${w.day} time`} onChange={e=>updateWindow(w.id,'time',e.target.value)} /></label><label>Minutes<input type="number" min="10" max="180" value={w.duration} onChange={e=>updateWindow(w.id,'duration',Number(e.target.value))}/></label><button className="icon" aria-label={`Remove ${w.day}`} onClick={()=>setWindows(state.windows.filter(x=>x.id!==w.id))}><Trash2/></button></article>)}</div><button className="secondary" onClick={()=>setWindows([...state.windows,{id:crypto.randomUUID(),day:'Saturday',date:'2',context:'Weekend walk',time:'10:00 AM',duration:45}])}><CirclePlus/> Add listening window</button></section>}
    {step === 2 && <section><h1>What do you want to hear?</h1><p>Choose genres, then add favourite shows, topics, and formats.</p><h3>Genres</h3><div className="choice-grid">{genres.map(g=><button className={pref.genres.includes(g)?'selected':''} onClick={()=>toggle('genres',g)} key={g}>{pref.genres.includes(g)&&<Check/>}{g}</button>)}</div><label className="full-label">Favourite shows<input placeholder="Search or type a show" value={showInput} onChange={e=>setShowInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&showInput){e.preventDefault();setPref({shows:[...pref.shows,showInput]});setShowInput('')}}}/></label><div className="tags editable">{pref.shows.map(x=><span key={x}>{x}<button aria-label={`Remove ${x}`} onClick={()=>setPref({shows:pref.shows.filter(y=>y!==x)})}><X/></button></span>)}</div><h3>Preferred formats</h3><div className="choice-grid">{['Documentary','Interviews','Narrative','Roundtable','Short daily'].map(x=><button className={pref.formats.includes(x)?'selected':''} onClick={()=>toggle('formats',x)} key={x}>{x}</button>)}</div></section>}
    {step === 3 && <section><h1>How should we build your stack?</h1><p>Set the rules once. You can change them anytime.</p><div className="rules">{[['newReleases','Prioritize new releases','Favor episodes published in the last seven days.'],['explicit','Avoid explicit content','Filter episodes marked explicit.'],['newShows','Mix in new shows','Add an occasional pick beyond your favourites.'],['serialized','Avoid serialized seasons','Skip episodes that require starting from episode one.'],['heard','Skip episodes already heard','Keep previously completed episodes out of your stack.']].map(([key,label,help])=><label className="toggle" key={key}><span><b>{label}</b><small>{help}</small></span><input type="checkbox" checked={pref.rules[key]} onChange={e=>setPref({rules:{...pref.rules,[key]:e.target.checked}})}/></label>)}</div><div className="lengths"><label>Minimum episode length<input type="number" value={pref.rules.min} onChange={e=>setPref({rules:{...pref.rules,min:Number(e.target.value)}})}/></label><label>Maximum episode length<input type="number" value={pref.rules.max} onChange={e=>setPref({rules:{...pref.rules,max:Number(e.target.value)}})}/></label></div><label className="full-label">Excluded topics<input placeholder="Add topics you would rather skip" value={pref.exclusions?.join(', ')||''} onChange={e=>setPref({exclusions:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/></label></section>}
    {step === 4 && <section><h1>Where do you usually listen?</h1><p>We’ll use this app for every main episode button.</p><div className="service-list">{services.map(s=><button className={state.service===s?'selected':''} onClick={()=>patch({service:s})} key={s}><span>{s}</span>{state.service===s&&<Check/>}</button>)}</div></section>}
    {step === 5 && <section className="ready"><LoadingStack/><h1>Ready to start stacking?</h1><p>Your next listens, stacked and ready. Your weekly plan will stay put until you edit or rebuild it.</p><button className="primary" onClick={build}>Build my first stack <ArrowRight/></button></section>}
    {step < 5 && <div className="onboard-next"><button className="primary" disabled={step===1&&!state.windows.length} onClick={()=>setStep(step+1)}>Continue <ArrowRight/></button></div>}
  </main>
}

function Today({ model, go }) { const {state,updateItem,swap}=model; const item=state.stack.find(x=>x.status!=='listened')||state.stack[0]; if(!item)return <Empty go={go}/>; return <main className="product page"><p className="eyebrow">GOOD MORNING, {state.name.toUpperCase()}</p><h1>{item.day}’s listen is ready.</h1><div className="today-grid"><article className="today-card"><div className="today-art"><Artwork item={item}/><span>{item.episodeDuration} min</span></div><div><small>{item.show}</small><h2>{item.title}</h2><div className="context"><Clock3/><span><b>{item.context}</b>{item.time} · {item.duration} minutes available</span></div><Tags items={[...item.reasons, state.preferences.genres[0]]}/><ListenLink item={item} service={state.service}/><div className="secondary-actions"><button onClick={()=>swap(item.id)}><RefreshCw/>Swap episode</button><button onClick={()=>updateItem(item.id,{status:'listened'})}><Check/>Mark as listened</button><button onClick={()=>go('stack')}>View full stack<ChevronRight/></button></div></div></article><aside><p className="eyebrow">COMING UP</p><h2>The rest of your week</h2>{state.stack.filter(x=>x.id!==item.id).slice(0,4).map(x=><button className="up-next" onClick={()=>go('stack')} key={x.id}><b>{x.day.slice(0,3)} {x.date}</b><span>{x.title}<small>{x.show} · {x.episodeDuration} min</small></span><ChevronRight/></button>)}</aside></div></main> }

function Empty({go}) { return <main className="center-page"><h1>A fresh stack, ready when you are.</h1><button className="primary" onClick={()=>go('onboarding')}>Start stacking</button></main> }
function Stack({model,go}) { const {state,patch,updateItem,swap}=model; const total=state.stack.reduce((a,x)=>a+x.episodeDuration,0); const remove=id=>patch({stack:state.stack.filter(x=>x.id!==id)}); const move=(item,index)=>{const copy=state.stack.filter(x=>x.id!==item.id);copy.splice(Math.min(index+1,copy.length),0,item);patch({stack:copy})}; return <main className="product page"><div className="page-heading"><div><p className="eyebrow">THIS WEEK’S LISTENING PLAN</p><h1>Your week is ready.</h1><p>{state.stack.length} episodes selected for {Math.floor(total/60)} hours and {total%60} minutes of listening.</p></div><div><button className="secondary" onClick={()=>go('profile')}><Settings2/>Edit my listening plan</button><button className="primary compact" onClick={()=>patch({stack:buildStack(state.windows,1)})}><RefreshCw/>Rebuild full stack</button></div></div><div className="full-stack">{state.stack.map((item,index)=><article className={`stack-item ${item.status==='listened'?'listened':''}`} key={item.id}><div className="stack-date"><b>{item.day.toUpperCase()}</b><strong>{item.date}</strong><span>{item.context}<small>{item.time} · {item.duration} min available</small></span></div><Artwork item={item}/><div className="stack-info"><small>{item.show}</small><h2>{item.title}</h2><p>{item.episodeDuration} min</p><Tags items={item.reasons}/></div><div className="stack-actions"><ListenLink item={item} service={state.service} compact/><div><button onClick={()=>swap(item.id)}><RefreshCw/> Swap</button><button onClick={()=>move(item,index)}><MoveRight/> Move</button><button onClick={()=>updateItem(item.id,{status:item.status==='listened'?'planned':'listened'})}><Check/> {item.status==='listened'?'Undo listened':'Listened'}</button><button onClick={()=>remove(item.id)}><Trash2/> Remove</button></div></div></article>)}</div><button className="add-weekend" onClick={()=>patch({stack:[...state.stack,...buildStack([{id:'sat',day:'Saturday',date:'2',context:'Weekend walk',time:'10:00 AM',duration:50}],3)]})}><CalendarPlus/>Add a weekend listen</button><section className="fit"><div><p className="eyebrow">PLANNED TO FIT YOUR WEEK</p><h2>Chosen for you, not at random.</h2></div><p>Every pick respects your available time, listening rules, favourite shows, and what you have already heard.</p></section></main> }

function Discover({model}) { const {state,patch}=model; const [notice,setNotice]=useState(''); const add=(item,target)=>{if(target==='saved')patch({saved:[...state.saved,item]});if(target==='next')patch({nextWeek:[...state.nextWeek,item]});if(target==='week')patch({stack:[...state.stack,{...item,id:`added-${Date.now()}`}]});setNotice(`${item.title} added to ${target==='week'?'this week':target==='next'?'next week':'saved for later'}.`)}; return <main className="product page"><p className="eyebrow">DISCOVER WITH A PURPOSE</p><h1>Find something worth adding.</h1><p>Recommendations that fit your plan—not an endless directory.</p><div className="discover-grid">{discoveries.map(item=><article className="discovery" key={item.id}><Artwork item={item}/><div><small>{item.show}</small><h2>{item.title}</h2><p>{item.episodeDuration} min</p><Tags items={item.reasons}/><div className="add-actions"><button className="primary compact" onClick={()=>add(item,'week')}>Add to this week</button><button onClick={()=>add(item,'next')}>Next week</button><button onClick={()=>add(item,'saved')}>Save for later</button></div></div></article>)}</div><div className="status" role="status">{notice}</div></main> }

function Profile({model,go}) { const {state,patch,reset}=model; const pref=state.preferences; return <main className="product page profile"><p className="eyebrow">ACCOUNT & PREFERENCES</p><h1>Your listening plan.</h1><div className="profile-grid"><section><h2>Profile</h2><label>Display name<input value={state.name} onChange={e=>patch({name:e.target.value})}/></label><label>Preferred listening app<select value={state.service} onChange={e=>patch({service:e.target.value})}>{services.map(x=><option key={x}>{x}</option>)}</select></label></section><section><h2>Listening taste</h2><label>Genres<input value={pref.genres.join(', ')} onChange={e=>patch({preferences:{...pref,genres:e.target.value.split(',').map(x=>x.trim())}})}/></label><label>Favourite shows<input value={pref.shows.join(', ')} onChange={e=>patch({preferences:{...pref,shows:e.target.value.split(',').map(x=>x.trim())}})}/></label><label>Excluded topics<input value={pref.exclusions?.join(', ')||''} onChange={e=>patch({preferences:{...pref,exclusions:e.target.value.split(',').map(x=>x.trim())}})}/></label></section><section><h2>Routine & rules</h2><p>{state.windows.length} listening windows · {pref.rules.min}–{pref.rules.max} minute episodes</p><button className="secondary" onClick={()=>go('onboarding')}>Edit routine and listening rules</button></section><section><h2>Saved for later</h2><p>{state.saved.length} saved episode{state.saved.length===1?'':'s'}</p></section></div><div className="danger"><h2>Prototype data</h2><p>Reset all locally saved preferences, listening history, and stacks on this device.</p><button onClick={()=>{reset();go('landing')}}><Trash2/>Reset prototype data</button></div><button className="signout" onClick={()=>{patch({prototypeSignedIn:false});go('landing')}}><LogOut/>Sign out</button></main> }

function Auth({type,model,go}) { const {state,patch}=model; const submit=e=>{e.preventDefault();go('check')}; if(type==='check')return <main className="center-page auth"><Logo/><p className="success"><Check/> EMAIL SENT</p><h1>Check your email.</h1><p>We sent a secure sign-in link to <b>{state.email||'you@example.com'}</b>. This prototype does not send a real email.</p><button className="secondary" onClick={()=>{patch({prototypeSignedIn:true});go('today')}}>Continue to prototype</button></main>; return <main className="center-page auth"><Logo/><h1>{type==='signin'?'Welcome back.':'Save your stack.'}</h1><p>{type==='signin'?'Enter your email and we’ll send a secure sign-in link.':'Continue with email to keep your plan, preferences, and listening history.'}</p><form onSubmit={submit}><label>Email address<input required type="email" placeholder="you@example.com" value={state.email} onChange={e=>patch({email:e.target.value})}/></label><button className="primary" type="submit">Email me a secure link</button></form><small>No password required. Email delivery is placeholder functionality.</small></main> }

export default function App(){ const model=usePrototype(); const [route,go]=useRoute(); const signed=['today','stack','discover','profile'].includes(route); let content; if(route==='landing')content=<Landing go={go}/>; else if(route==='onboarding')content=<Onboarding model={model} go={go}/>; else if(route==='today')content=<Today model={model} go={go}/>; else if(route==='stack')content=<Stack model={model} go={go}/>; else if(route==='discover')content=<Discover model={model}/>; else if(route==='profile')content=<Profile model={model} go={go}/>; else content=<Auth type={route==='check'?'check':route==='signin'?'signin':'email'} model={model} go={go}/>; return <><Nav route={route} go={go} signedIn={signed}/>{content}<footer><Logo/><p>Your podcast app plays it. Podstack plans it.</p><span>© 2026 Podstack</span></footer></> }
